;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-append
        evil-change
        evil-delete
        evil-insert
        evil-next-line
        evil-normal-state
        evil-yank
        ))

(setq mc/cmds-to-run-once
      '(
        evil-backward-char
        evil-downcase
        evil-ex
        evil-force-normal-state
        evil-forward-char
        evil-previous-line
        evil-ret
        helm-M-x
        undefined
        ))
